/*
  Auto-generated by Spline
*/
import * as THREE from 'three'
import {React, useState, useRef, useEffect} from 'react'
import useSpline from '@splinetool/r3f-spline'
import { OrthographicCamera, PerspectiveCamera } from '@react-three/drei'
import {colorMaterial_R,colorMaterial_G,colorMaterial_B} from './ColorPicker'
import {
  RecoilRoot,
  atom,
  selector,
  useRecoilState,
  useRecoilValue,
} from "recoil"
import { PartState, colorState } from './state';

export default function Scene({ ...props }) {
  const [ShoePart, setShoePart] = useRecoilState(PartState);
  const [color, setColor] = useRecoilState(colorState);
  const colorUpdate = new THREE.Color(color);
  const { nodes, materials } = useSpline('https://prod.spline.design/CXn8xUxZDVxWpuRy/scene.splinecode')
  
  const Colormaterial = new THREE.MeshLambertMaterial({color:colorUpdate});
  // if(ShoePart === THREE.Object3D.name){
  //   console.log("HOOOOO");
  //   this.THREE.Object3D.material = Colormaterial('#00ffff');
  // }

  const partChange = name =>{
    if(ShoePart === name){
    }

    console.log(name + "1")
  }
  console.log(ShoePart);

  const meshRef = useRef();
  useEffect(() =>  {
    if(meshRef.current) {
      const meshName = meshRef.current.name;
      console.log("Mesh의 name: ",meshName);
      if(meshName === ShoePart){
        console.log("ShoePart name: ",meshName);
        meshRef.current.material = new THREE.MeshLambertMaterial({color:"#ffffff"});
      }
    }
  }, [meshRef.current]);


  return (
    <>

      <color attach="background" args={['#333333']} />
      <group {...props} dispose={null}>
        <scene name="Scene 1">
        <spotLight
            name="Spot Light"
            castShadow
            intensity={1.6}
            angle={0.37}
            distance={2006}
            shadow-mapSize-width={1024}
            shadow-mapSize-height={1024}
            shadow-camera-fov={119.99999999999999}
            shadow-camera-near={100}
            shadow-camera-far={100000}
            position={[0, 1711.98, 0]}
          />
          <PerspectiveCamera
            name="Camera"
            makeDefault={true}
            far={100000}
            near={70}
            fov={45}
            position={[2924.39, 1477.48, 997.08]}
            rotation={[-0.98, 1.02, 0.9]}
            scale={1}
          />
          <group name="Nike_Air_Force_1_Low" position={[700, -1200, -300]} scale={100}>
            {/* 왼쪽 신발끈 */}
            <mesh
              name="Sole"
              ref = {meshRef}
              geometry={nodes['Nike_Air_Force_1_Set_White:Shoelaces_L1'].geometry}
              //<meshBasicMaterial attach="material" color={color} />
              // material={ 
              //   ShoePart === "Sole" ? Colormaterial : nodes['Nike_Air_Force_1_Set_White:Shoelaces_L1'].material
              // }
              material={Colormaterial}
              onUpdate={partChange()}
              castShadow
              receiveShadow
            />
            {/* 오른쪽 젤 넓은 부분 */}
            <mesh
              name="Nike_Air_Force_1_Set_White:Leather_R1"
              geometry={nodes['Nike_Air_Force_1_Set_White:Leather_R1'].geometry}
              material={Colormaterial}
              castShadow
              receiveShadow
            />
            {/* 왼쪽 신발 입구 */}
            <mesh
              name="Nike_Air_Force_1_Set_White:Inner_Fabrick_L1"
              geometry={nodes['Nike_Air_Force_1_Set_White:Inner_Fabrick_L1'].geometry}
              material={Colormaterial}
              castShadow
              receiveShadow
            />
            {/* 왼쪽 젤 넓은 부분 */}
            <mesh
              name="Nike_Air_Force_1_Set_White:Leather_L1"
              geometry={nodes['Nike_Air_Force_1_Set_White:Leather_L1'].geometry}
              material={Colormaterial}
              castShadow
              receiveShadow
            />
            {/* 왼쪽 밑참 실 */}
            <mesh
              name="Nike_Air_Force_1_Set_White:Thread_Sole_L1"
              geometry={nodes['Nike_Air_Force_1_Set_White:Thread_Sole_L1'].geometry}
              material={Colormaterial}
              castShadow
              receiveShadow
            />
            {/* 오른쪽 끈 중간 라밸 */}
            <mesh
              name="Nike_Air_Force_1_Set_White:Metal_Label_R1"
              geometry={nodes['Nike_Air_Force_1_Set_White:Metal_Label_R1'].geometry}
              material={Colormaterial}
              castShadow
              receiveShadow
            />
            {/* 왼쪽 끈 중간 라벨 */}
            <mesh
              name="Nike_Air_Force_1_Set_White:Metal_Label_L1"
              geometry={nodes['Nike_Air_Force_1_Set_White:Metal_Label_L1'].geometry}
              material={Colormaterial}
              castShadow
              receiveShadow
            />
            {/* 오른쪽 밑참 실 */}
            <mesh
              name="Nike_Air_Force_1_Set_White:Thread_Sole_R1"
              geometry={nodes['Nike_Air_Force_1_Set_White:Thread_Sole_R1'].geometry}
              material={Colormaterial}
              castShadow
              receiveShadow
            />
            {/* 왼쪽 신발끈 밑에 부분_설포 */}
            <mesh
              name="Nike_Air_Force_1_Set_White:Tongue_L1"
              geometry={nodes['Nike_Air_Force_1_Set_White:Tongue_L1'].geometry}
              material={Colormaterial}
              castShadow
              receiveShadow
            />
            {/* 왼쪽 설포 쪽에 있는 라벨 */}
            <mesh
              name="Nike_Air_Force_1_Set_White:Label_L1"
              geometry={nodes['Nike_Air_Force_1_Set_White:Label_L1'].geometry}
              material={Colormaterial}
              castShadow
              receiveShadow
            />
              {/* 오른쪽 신발끈 */}
            <mesh
              name="Nike_Air_Force_1_Set_White:Shoelaces_R1"
              geometry={nodes['Nike_Air_Force_1_Set_White:Shoelaces_R1'].geometry}
              material={Colormaterial}
              castShadow
              receiveShadow
            />
            {/* 오른쪽 신발끈 밑에 부분_설포 */}
            <mesh
              name="Nike_Air_Force_1_Set_White:Tongue_R1"
              geometry={nodes['Nike_Air_Force_1_Set_White:Tongue_R1'].geometry}
              material={Colormaterial}
              castShadow
              receiveShadow
            />
            {/* 오른쪽 안창_깔창 */}
            <mesh
              name="Nike_Air_Force_1_Set_White:Insole_R1"
              geometry={nodes['Nike_Air_Force_1_Set_White:Insole_R1'].geometry}
              material={Colormaterial}
              castShadow
              receiveShadow
            />
            {/* 왼쪽 밑창 */}
            <mesh
              name="Nike_Air_Force_1_Set_White:Sole_L1"
              geometry={nodes['Nike_Air_Force_1_Set_White:Sole_L1'].geometry}
              material={Colormaterial}
              castShadow
              receiveShadow
            />
            {/* 오른쪽 신발 입구 */}
            <mesh
              name="Nike_Air_Force_1_Set_White:Inner_Fabrick_R1"
              geometry={nodes['Nike_Air_Force_1_Set_White:Inner_Fabrick_R1'].geometry}
              material={Colormaterial}
              castShadow
              receiveShadow
            />
            {/* 오른쪽 설포 쪽에 있는 라벨 */}
            <mesh
              name="Nike_Air_Force_1_Set_White:Label_R1"
              geometry={nodes['Nike_Air_Force_1_Set_White:Label_R1'].geometry}
              material={Colormaterial}
              castShadow
              receiveShadow
            />
            {/* 왼쪽 안창_깔창 */}
            <mesh
              name="Nike_Air_Force_1_Set_White:Insole_L1"
              geometry={nodes['Nike_Air_Force_1_Set_White:Insole_L1'].geometry}
              material={Colormaterial}
              castShadow
              receiveShadow
            />
            {/* 오른쪽 밑창 */}
            <mesh
              name="Nike_Air_Force_1_Set_White:Sole_R1"
              geometry={nodes['Nike_Air_Force_1_Set_White:Sole_R1'].geometry}
              material={Colormaterial}
              castShadow
              receiveShadow
            />
          </group>
          <directionalLight
            name="Directional Light"
            castShadow
            intensity={0.77}
            shadow-mapSize-width={1024}
            shadow-mapSize-height={1024}
            shadow-camera-near={-10000}
            shadow-camera-far={100000}
            shadow-camera-left={-1000}
            shadow-camera-right={1000}
            shadow-camera-top={1000}
            shadow-camera-bottom={-1000}
            position={[200, 300, 300]}
          />
          <OrthographicCamera name="1" makeDefault={false} far={10000} near={-50000} />
          <hemisphereLight name="Default Ambient Light" intensity={0.16} color="#eaeaea" />
        </scene>
      </group>
    </>
  )
}
