/*
  Auto-generated by Spline
*/
import * as THREE from 'three'
import {React, useState, useRef, useEffect} from 'react'
import useSpline from '@splinetool/r3f-spline'
import { OrthographicCamera, PerspectiveCamera } from '@react-three/drei'
import {colorMaterial_R,colorMaterial_G,colorMaterial_B} from './ColorPicker'
import {
  RecoilRoot,
  atom,
  selector,
  useRecoilState, useRecoilValue,
} from "recoil"
import { colorState_ShoelacesR, 
  colorState_LeatherR, 
  colorState_InnerFabrickR, 
  colorState_ThreadSoleR,
  colorState_MetalLabelR,
  colorState_TongueR,
  colorState_LabelR,
  colorState_InsoleR,
  colorState_SoleR,
  colorState_ShoelacesL, 
  colorState_LeatherL, 
  colorState_InnerFabrickL, 
  colorState_ThreadSoleL,
  colorState_MetalLabelL,
  colorState_TongueL,
  colorState_LabelL,
  colorState_InsoleL,
  colorState_SoleL,
  PartState,
  SelectCamera,
  TopBool,
  WholeBool,
  RightBool
} from './state';

export default function Scene({ ...props }) {
  const [ShoePart, setShoePart] = useRecoilState(PartState);
  const [selectCamera, setCamera] = useRecoilState(SelectCamera);
  const [wholeBool, setWholeBool] = useRecoilState(WholeBool);
  const [topBool, setTopBool] = useRecoilState(TopBool);
  const [rightBool, setRightBool] = useRecoilState(RightBool);


  const [Color_ShoelacesR, setColor_ShoelacesR] = useRecoilState(colorState_ShoelacesR); //obj로 넘어가는 값
  const [Color_LeatherR, setColor_LeatherR] = useRecoilState(colorState_LeatherR);
  const [Color_InnerFabrickR, setColor_InnerFabrickR] = useRecoilState(colorState_InnerFabrickR);
  const [Color_ThreadSoleR, setColor_ThreadSoleR] = useRecoilState(colorState_ThreadSoleR);
  const [Color_MetalLabelR, setColor_MetalLabelR] = useRecoilState(colorState_MetalLabelR);
  const [Color_TongueR, setColor_TongueR] = useRecoilState(colorState_TongueR);
  const [Color_LabelR, setColor_LabelR] = useRecoilState(colorState_LabelR);
  const [Color_InsoleR, setColor_InsoleR] = useRecoilState(colorState_InsoleR);
  const [Color_SoleR, setColor_SoleR] = useRecoilState(colorState_SoleR);
  const [Color_ShoelacesL, setColor_ShoelacesL] = useRecoilState(colorState_ShoelacesL);
  const [Color_LeatherL, setColor_LeatherL] = useRecoilState(colorState_LeatherL);
  const [Color_InnerFabrickL, setColor_InnerFabrickL] = useRecoilState(colorState_InnerFabrickL);
  const [Color_ThreadSoleL, setColor_ThreadSoleL] = useRecoilState(colorState_ThreadSoleL);
  const [Color_MetalLabelL, setColor_MetalLabelL] = useRecoilState(colorState_MetalLabelL);
  const [Color_TongueL, setColor_TongueL] = useRecoilState(colorState_TongueL);
  const [Color_LabelL, setColor_LabelL] = useRecoilState(colorState_LabelL);
  const [Color_InsoleL, setColor_InsoleL] = useRecoilState(colorState_InsoleL);
  const [Color_Sole, setColor_SoleL] = useRecoilState(colorState_SoleL);

  const colorUpdate1 = new THREE.Color(Color_ShoelacesR);
  const colorUpdate2 = new THREE.Color(Color_LeatherR);
  const colorUpdate3 = new THREE.Color(Color_InnerFabrickR);
  const colorUpdate4 = new THREE.Color(Color_ThreadSoleR);
  const colorUpdate5 = new THREE.Color(Color_MetalLabelR);
  const colorUpdate6 = new THREE.Color(Color_TongueR);
  const colorUpdate7 = new THREE.Color(Color_LabelR);
  const colorUpdate8 = new THREE.Color(Color_InsoleR);
  const colorUpdate9 = new THREE.Color(Color_SoleR);

  const colorUpdate10 = new THREE.Color(Color_ShoelacesL);
  const colorUpdate11 = new THREE.Color(Color_LeatherL);
  const colorUpdate12 = new THREE.Color(Color_InnerFabrickL);
  const colorUpdate13 = new THREE.Color(Color_ThreadSoleL);
  const colorUpdate14 = new THREE.Color(Color_MetalLabelL);
  const colorUpdate15 = new THREE.Color(Color_TongueL);
  const colorUpdate16 = new THREE.Color(Color_LabelL);
  const colorUpdate17 = new THREE.Color(Color_InsoleL);
  const colorUpdate18 = new THREE.Color(Color_Sole);

  const { nodes, materials } = useSpline('https://prod.spline.design/CXn8xUxZDVxWpuRy/scene.splinecode')
  
  const Colormaterial1 = new THREE.MeshLambertMaterial({color:colorUpdate1});
  const Colormaterial2 = new THREE.MeshLambertMaterial({color:colorUpdate2});
  const Colormaterial3 = new THREE.MeshLambertMaterial({color:colorUpdate3});
  const Colormaterial4 = new THREE.MeshLambertMaterial({color:colorUpdate4});
  const Colormaterial5 = new THREE.MeshLambertMaterial({color:colorUpdate5});
  const Colormaterial6 = new THREE.MeshLambertMaterial({color:colorUpdate6});
  const Colormaterial7 = new THREE.MeshLambertMaterial({color:colorUpdate7});
  const Colormaterial8 = new THREE.MeshLambertMaterial({color:colorUpdate8});
  const Colormaterial9 = new THREE.MeshLambertMaterial({color:colorUpdate9});

  const Colormaterial10 = new THREE.MeshLambertMaterial({color:colorUpdate10});
  const Colormaterial11 = new THREE.MeshLambertMaterial({color:colorUpdate11});
  const Colormaterial12 = new THREE.MeshLambertMaterial({color:colorUpdate12});
  const Colormaterial13 = new THREE.MeshLambertMaterial({color:colorUpdate13});
  const Colormaterial14 = new THREE.MeshLambertMaterial({color:colorUpdate14});
  const Colormaterial15 = new THREE.MeshLambertMaterial({color:colorUpdate15});
  const Colormaterial16 = new THREE.MeshLambertMaterial({color:colorUpdate16});
  const Colormaterial17 = new THREE.MeshLambertMaterial({color:colorUpdate17});
  const Colormaterial18 = new THREE.MeshLambertMaterial({color:colorUpdate18});

  // let WholeCameraBool = true;
  // let TopCameraBool = false;
  // let RightCameraBool = false;
  // let LeftCameraBool = false;
  // let BackCameraBool = false;
  // let FrontCameraBool = false;



  // if(SelectCamera === 'WholeCamera'){
  //   WholeCameraBool = true;
  // }else if(SelectCamera === 'TopCamera'){
  //   TopCameraBool = true;
  // }

  // useEffect(() => {
  //   if(SelectCamera === 'WholeCamera'){
  //     WholeCameraBool = true;
  //   }else if(SelectCamera === 'TopCamera'){
  //     TopCameraBool = true;
  //   }
  // }, [WholeCameraBool, TopCameraBool])
  // if(ShoePart === THREE.Object3D.name){
  //   console.log("HOOOOO");
  //   this.THREE.Object3D.material = Colormaterial('#00ffff');
  // }
  // const wholeCameraRef = useRef();
  // const rightCameraRef = useRef();
  // const leftCameraRef = useRef();
  // useEffect(() => {
  //   const cameras = [rightCameraRef, leftCameraRef]
  //   cameras.forEach(cameraRef =>{
  //     if(cameraRef.current.name === selectCamera){
  //       cameraRef.current.makeDefault = true;
  //       console.log("camera: " + cameraRef.current.name);
  //       console.log("camera: " + cameraRef.current.makeDefault)
  //     }else if(cameraRef.current.name !== selectCamera){
  //       cameraRef.current.makeDefault = false;
  //       console.log(cameraRef.current.makeDefault)
  //       console.log(cameraRef.current.name)
  //     }
  //   })
  //   console.log(selectCamera);
  // }, [selectCamera, rightCameraRef.current.makeDefault, leftCameraRef.current.makeDefault])
  // useEffect(() => {
  //   const switchCamera = (cameraRef) => {
  //     const cameras = [leftCameraRef, rightCameraRef /*... 다른 카메라 ref 추가 */];
  //     cameras.forEach(camera => {
  //       if (cameraRef.current && cameraRef.current.name === selectCamera) {
  //         cameraRef.current.makeDefault = true;
  //       } else {
  //         camera.current.makeDefault = false;
  //       }
  //     });
  //   };
  //   // 선택된 카메라 이름이 변경될 때 switchCamera 함수 호출
  //   switchCamera((selectCamera + 'Ref')); // 예를 들어, 'wholeCameraRef'를 평가하여 wholeCameraRef를 가져옴
  // }, [selectCamera]);

  // useEffect(() =>  {
  //   if(CameraRef.current) {
  //     const currentCamera = CameraRef.current;
  //     const nextCamera = selectCamera;
  //     const CameraState = CameraRef.current.makeDefault;
  //     console.log(CameraRef.makeDefault)
  //     console.log(currentCamera.name);
  //     if (currentCamera.makeDefault === 'true'){
  //       console.log("카메라 : ", currentCamera.name);
  //     }
  //     if(currentCamera === ''){
  //       console.log("현재 카메라 : ", currentCamera.name);
  //       console.log("다음 카메라 : ",nextCamera);
  //     }
     

  //   }
  // }, [CameraRef.current]);


  // useEffect(() => {
  //   // meshRef.current를 통해 Three.js PerspectiveCamera에 접근
  //   const camera = meshRef.current;
  
  //   // 카메라의 위치를 출력하는 함수
  //   const logCameraPosition = () => {
  //     if (camera) {
  //       console.log('카메라 위치:', camera.position.toArray());
  //     }
  //   };
  
  //   // 위치를 주기적으로 확인하고 싶을 때 setInterval을 이용
  //   const interval = setInterval(logCameraPosition, 5000); // 1초마다 위치 확인
  
  //   return () => {
  //     clearInterval(interval); // 컴포넌트가 unmount될 때 interval 정리
  //   };
  // }, []);

  return (
    <>

      <color attach="background" args={['#333333']} />
      <group {...props} dispose={null}>
        <scene name="Scene 1">
        <PerspectiveCamera
            name="wholeCamera"
            makeDefault={wholeBool}
            // ref={wholeCameraRef}
            far={100000}
            near={70}
            fov={13}
            up={[0, 1, 0]}
            position={[867.2, 3394.47, 3509.33]}
            rotation={[-0.75, 0.28, 0.26]}
          />
          <OrthographicCamera
            name="topCamera"
            makeDefault={topBool}
            // ref={CameraRef}
            zoom={0.5}
            far={100000}
            near={-100000}
            up={[0, 1, 0]}
            position={[0, 500, 0]}
            rotation={[0, 0, 0]}
          />
          <OrthographicCamera
            name="rightCamera"
            makeDefault={rightBool}
            // ref={rightCameraRef}
            zoom={0.5}
            far={100000}
            near={-100000}
            up={[0, 1, 0]}
            position={[-3740.48, 855.05, -397.95]}
            rotation={[-2.11, -1.35, -2.13]}
          />
          <OrthographicCamera
            name="backCamera"
            makeDefault={false}
            // ref={CameraRef}
            zoom={0.5}
            far={100000}
            near={-100000}
            up={[0, 1, 0]}
            position={[0, 1000, -15000]}
            rotation={[0, 0, 0]}
            scale={1}
          />
          <OrthographicCamera
            name="leftCamera"
            makeDefault={false}
            // ref={leftCameraRef}
            zoom={0.5}
            far={100000}
            near={-100000}
            position={[3000, 964.48, -89.53]}
            rotation={[-1.68, 1.36, 1.68]}
            scale={1}
          />
          <OrthographicCamera
            name="frontCamera"
            makeDefault={false}
            // ref={CameraRef}
            zoom={0.5}
            far={100000}
            near={-100000}
            up={[0, 1, 0]}
            position={[0, 0, 0]}
            rotation={[0, 0, 0]}
          />
          <spotLight
            name="Spot Light"
            castShadow
            intensity={1.6}
            angle={0.37}
            distance={2006}
            shadow-mapSize-width={1024}
            shadow-mapSize-height={1024}
            shadow-camera-fov={119.99999999999999}
            shadow-camera-near={100}
            shadow-camera-far={100000}
            position={[-551.11, 1641.98, 0]}
          />

  <group name="Nike_Air_Force_1_Low" position={[700, -200, 0]} scale={30}>
            {/* 오른쪽 신발끈 */}
            <mesh
              name="Nike_Air_Force_1_Set_White:Shoelaces_R1"
              geometry={nodes['Nike_Air_Force_1_Set_White:Shoelaces_R1'].geometry}
              material={Colormaterial1}
              castShadow
              receiveShadow
            />            
            {/* 오른쪽 젤 넓은 부분 */}
            <mesh
              name="Nike_Air_Force_1_Set_White:Leather_R1"
              geometry={nodes['Nike_Air_Force_1_Set_White:Leather_R1'].geometry}
              material={Colormaterial2}
              castShadow
              receiveShadow
            />
            {/* 오른쪽 신발 입구 */}
            <mesh
              name="Nike_Air_Force_1_Set_White:Inner_Fabrick_R1"
              geometry={nodes['Nike_Air_Force_1_Set_White:Inner_Fabrick_R1'].geometry}
              material={Colormaterial3}
              castShadow
              receiveShadow
            />
            {/* 오른쪽 밑참 실 */}
            <mesh
              name="Nike_Air_Force_1_Set_White:Thread_Sole_R1"
              geometry={nodes['Nike_Air_Force_1_Set_White:Thread_Sole_R1'].geometry}
              material={Colormaterial4}
              castShadow
              receiveShadow
            />
            {/* 오른쪽 끈 중간 라밸 */}
            <mesh
              name="Nike_Air_Force_1_Set_White:Metal_Label_R1"
              geometry={nodes['Nike_Air_Force_1_Set_White:Metal_Label_R1'].geometry}
              material={Colormaterial5}
              castShadow
              receiveShadow
            />
            {/* 오른쪽 신발끈 밑에 부분_설포 */}
            <mesh
              name="Nike_Air_Force_1_Set_White:Tongue_R1"
              geometry={nodes['Nike_Air_Force_1_Set_White:Tongue_R1'].geometry}
              material={Colormaterial6}
              castShadow
              receiveShadow
            />
            {/* 오른쪽 설포 쪽에 있는 라벨 */}
            <mesh
              name="Nike_Air_Force_1_Set_White:Label_R1"
              geometry={nodes['Nike_Air_Force_1_Set_White:Label_R1'].geometry}
              material={Colormaterial7}
              castShadow
              receiveShadow
            />
            {/* 오른쪽 안창_깔창 */}
            <mesh
              name="Nike_Air_Force_1_Set_White:Insole_R1"
              geometry={nodes['Nike_Air_Force_1_Set_White:Insole_R1'].geometry}
              material={Colormaterial8}
              castShadow
              receiveShadow
            />
            {/* 오른쪽 밑창 */}
            <mesh
              name="Nike_Air_Force_1_Set_White:Sole_R1"
              geometry={nodes['Nike_Air_Force_1_Set_White:Sole_R1'].geometry}
              material={Colormaterial9}
              castShadow
              receiveShadow
            />

{/*------------------------------------------------------------------------------*/}
            {/* 왼쪽 신발끈 */}
            <mesh
              name="Sole"
              geometry={nodes['Nike_Air_Force_1_Set_White:Shoelaces_L1'].geometry}
              material={Colormaterial10}
              castShadow
              receiveShadow
            />
            {/* 왼쪽 젤 넓은 부분 */}
            <mesh
              name="Nike_Air_Force_1_Set_White:Leather_L1"
              geometry={nodes['Nike_Air_Force_1_Set_White:Leather_L1'].geometry}
              material={Colormaterial11}
              castShadow
              receiveShadow
            />            
            {/* 왼쪽 신발 입구 */}
            <mesh
              name="Nike_Air_Force_1_Set_White:Inner_Fabrick_L1"
              geometry={nodes['Nike_Air_Force_1_Set_White:Inner_Fabrick_L1'].geometry}
              material={Colormaterial12}
              castShadow
              receiveShadow
            />
            {/* 왼쪽 밑참 실 */}
            <mesh
              name="Nike_Air_Force_1_Set_White:Thread_Sole_L1"
              geometry={nodes['Nike_Air_Force_1_Set_White:Thread_Sole_L1'].geometry}
              material={Colormaterial13}
              castShadow
              receiveShadow
            />            
            {/* 왼쪽 끈 중간 라벨 */}
            <mesh
              name="Nike_Air_Force_1_Set_White:Metal_Label_L1"
              geometry={nodes['Nike_Air_Force_1_Set_White:Metal_Label_L1'].geometry}
              material={Colormaterial14}
              castShadow
              receiveShadow
            />
            {/* 왼쪽 신발끈 밑에 부분_설포 */}
            <mesh
              name="Nike_Air_Force_1_Set_White:Tongue_L1"
              geometry={nodes['Nike_Air_Force_1_Set_White:Tongue_L1'].geometry}
              material={Colormaterial15}
              castShadow
              receiveShadow
            />
            {/* 왼쪽 설포 쪽에 있는 라벨 */}
            <mesh
              name="Nike_Air_Force_1_Set_White:Label_L1"
              geometry={nodes['Nike_Air_Force_1_Set_White:Label_L1'].geometry}
              material={Colormaterial16}
              castShadow
              receiveShadow
            />
            {/* 왼쪽 안창_깔창 */}
            <mesh
              name="Nike_Air_Force_1_Set_White:Insole_L1"
              geometry={nodes['Nike_Air_Force_1_Set_White:Insole_L1'].geometry}
              material={Colormaterial17}
              castShadow
              receiveShadow
            />
            {/* 왼쪽 밑창 */}
            <mesh
              name="Nike_Air_Force_1_Set_White:Sole_L1"
              geometry={nodes['Nike_Air_Force_1_Set_White:Sole_L1'].geometry}
              material={Colormaterial18}
              castShadow
              receiveShadow
            />
          </group>
          <directionalLight
            name="Directional Light 2"
            castShadow
            intensity={0.7}
            shadow-mapSize-width={1024}
            shadow-mapSize-height={1024}
            shadow-camera-near={-10000}
            shadow-camera-far={100000}
            shadow-camera-left={-1000}
            shadow-camera-right={1000}
            shadow-camera-top={1000}
            shadow-camera-bottom={-1000}
            position={[1525.53, 620.48, -278.21]}
          />
          <directionalLight
            name="Directional Light 3"
            castShadow
            intensity={0.53}
            shadow-mapSize-width={1024}
            shadow-mapSize-height={1024}
            shadow-camera-near={-10000}
            shadow-camera-far={100000}
            shadow-camera-left={-1000}
            shadow-camera-right={1000}
            shadow-camera-top={1000}
            shadow-camera-bottom={-1000}
            position={[-2016.1, 230.99, -321.84]}
          />
          <directionalLight
            name="Directional Light"
            castShadow
            intensity={0.77}
            shadow-mapSize-width={1024}
            shadow-mapSize-height={1024}
            shadow-camera-near={-10000}
            shadow-camera-far={100000}
            shadow-camera-left={-1000}
            shadow-camera-right={1000}
            shadow-camera-top={1000}
            shadow-camera-bottom={-1000}
            position={[-128.42, 411.24, 334.55]}
          />

          <OrthographicCamera name="1" makeDefault={false} far={10000} near={-50000} />
          <hemisphereLight name="Default Ambient Light" intensity={0.16} color="#eaeaea" />
        </scene>
      </group>
    </>
  )
}
